1. values added:  20

2. final result:  20

3. values added:  20 

4. The final result in line 13 will throw an error since let has a block scope, and since the variable called result lives only within the first conditional. Line 13 involves  variable 'result' that is trying to be retrieved outside the scope, causing an error.

5. When replace to const, it will throw an error on line 9 becuase the const keyword prevents reassignment, and reassignment is attempted throughout the first condition for the function sumValues

6. Similarly to reponse 5, line 13 will also throw an error for the same reason, we cannot do reassignment

